### ISSUE TITLE
Expanding JSON benchmarks

### ISSUE THREAD

**Issue by Erotemic** [TkTech/json_benchmark#2]
I've started work on what is turning out to be a fairly intensive effort to generate high quality quantitative json benchmarks with graphs, tables, and multiple statistical analyses.

I'm currently working on the code as a PR to ujson: https://github.com/ultrajson/ultrajson/pull/542 but its getting involved so it might make sense to target it as a standalone repo. 

Adding simdjson to my current benchmarks shows an interesting (and expected) result: the value of SIMD kicks in when the data gets large: 

![image](https://user-images.githubusercontent.com/3186211/170883984-ad2a798a-40be-47ec-9a29-671408752b5c.png)

(Notice the red line in the left "loads" graph)

For dumps, because pysimdjson does not wrap the "dumps" and just uses "json.dumps", we get a line that maps almost exactly on top of the "json" line.

I'm writing this issue as an attempt to gauge interest in integrating my work here instead of "ujson" itself (or making yet another json benchmarking repo).

**Comment by TkTech** [comment]
Interesting! Certainly interested in expanding the benchmarks. I'll have to take a closer look at your approach when I have time on the weekend.
