### ISSUE TITLE
Benchmark results are out of date

### ISSUE THREAD

**Issue by jcrist** [TkTech/json_benchmark#7]
In #3 the version of msgspec in these benchmarks was updated, but the results are still showing for an older version. There's also a new-ish version of `orjson` out with some noticeable performance improvements (it's now mostly a thin wrapper around yyjson). It'd be good to get accurate results up.

Perhaps adding a "last run" date near the top of the report would be helpful in showing how up-to-date the results are?

**Comment by jcrist** [comment]
Thanks!

**Comment by TkTech** [comment]
Thank you for the reminder, these things tend to fall off the map.
